social:
  github: https://github.com/maoyuyang

author: emmm

powerd:
  name: mdoc
  github: https://github.com/maoyuyang/mdoc

avatar: /static/img/avatar.jpeg

signature: 知易行难啊

stylesheets:
  - /static/css/normalize.css
  - /static/icon/iconfont.css
  - /static/css/prism-tomorrow.css
  - /static/css/index.styl

scripts:
  - /static/js/index.js