social:
  github: https://github.com/maoyuyang

author: emmm

highlight: true

avatar: https://avatars0.githubusercontent.com/u/19368146?s=460&v=4

signature: 无可救药之人

stylesheets:
  - /static/css/index.css
  - /static/css/normalize.css
  - /static/icon/iconfont.css

scripts:
  - /static/js/index.js